project_id_base           : "track-atlas-ch"
org_id                    : "228410341324"
primary_region            : "us-central1"
primary_zone              : "us-central1-a"
shared_vpc_subnet_name    : "apps-tertiary"
shared_vpc_connector_name : "tertiary-nat-connector"
tenant                    : "devops"
delete_protection_flag    : true
logging_storage_bucket    : "org-devops-storage-logs-f6b88693"
mongo_major_version       : 4.2
