parent_folder_id       : "567401809730"
network_project_id     : "sand-network-830b"
network_name           : "ch-sand-network-xpn-host-1"
env                    : "sand"
environment            : "sandbox"
machine_type           : "e2-standard-2"
root_disk_size_gb      : "16"
delete_protection_flag : false
