const {createCSV} = require('./lib/csv');
const prompt = require('prompt');
const csv = require('csv-parser');
const fs = require('fs');
const EventEmitter = require('events');
const {default: PQueue} = require('p-queue');
const {
    MongoDBConnect, 
    Patients, 
    Encounters, 
    Interactions, 
    Enrollments, 
    CallAttempts, 
    ArchivedCallAttempts,
    PatientIssues,
    PatientEvents,
    UnitVisits
} = require('./lib/mongo_utils');
const {ObjectId} = require('mongodb');

const mongo_connection = new MongoDBConnect();

const documentCountFetchQ = new PQueue({concurrency: 10});

class MyEmitter extends EventEmitter {}
const myEmitter = new MyEmitter();

const results = {};
var params;

console.log("Create care provider report usage report for either 'test' or 'actual' care providers)");
console.log("This will use the care provider lists generated by filter_test_care_providers.js that are stored");
console.log("in directory, ./reports. If those files don't exist, first run filter_test_care_providers.js to generate");
console.log("those reports.");
console.log("usageType: 'test' or 'actual'");
console.log("outputFile: path to output file");
console.log('------------------------------------------------------------------------------------------');
prompt.start();
prompt.get(['usageType', 'outputFile'], function (err, result) {
    if (err) {
        console.error(err);
        process.exit();
    }
    params = result;
    console.log()

    let initialData = params.usageType === 'test' ? "./reports/test_demo_canceled_care_providers_list.csv" : "./reports/actual_care_providers_list.csv";

    fs.createReadStream(initialData)
    .pipe(csv())
    .on('data', (data) => {
        results[data.ID] = data;
    })
    .on('end', () => {
        myEmitter.emit('start');
    });
});

async function fetchDocumentStats() {
    const mongo_connection = new MongoDBConnect();
    try {
        await mongo_connection.connect();
        console.log("Connected to Mongo");
    
        const patients = new Patients(mongo_connection);
        const encounters = new Encounters(mongo_connection);
        const interactions = new Interactions(mongo_connection);
        const enrollments = new Enrollments(mongo_connection);
        const call_attempts = new CallAttempts(mongo_connection);
        const archived_call_attempts = new ArchivedCallAttempts(mongo_connection);
        const patient_issues = new PatientIssues(mongo_connection);
        const patient_events = new PatientEvents(mongo_connection);
        const unit_visits = new UnitVisits(mongo_connection);
    
        const keys = Object.keys(results);
    
        funcs = keys.map(key => {
            const query = {care_provider_id: ObjectId(key)};
            return [
                async () => {
                    let docCount = await patients.countDocuments(query);
                    myEmitter.emit('count', key, "patientCount", docCount);
                },
                async () => {
                    let docCount = await encounters.countDocuments(query);
                    myEmitter.emit('count', key, "encounterCount", docCount);
                },
                async () => {
                    let docCount = await interactions.countDocuments(query);
                    myEmitter.emit('count', key, "interactionCount", docCount);
                },
                async () => {
                    let docCount = await enrollments.countDocuments(query);
                    myEmitter.emit('count', key, "enrollmentsCount", docCount);
                },
                async () => {
                    let docCount = await call_attempts.countDocuments(query);
                    myEmitter.emit('count', key, "callAttemptsCount", docCount);
                },
                async () => {
                    let docCount = await archived_call_attempts.countDocuments(query);
                    myEmitter.emit('count', key, "archivedCallAttemptsCount", docCount);
                },
                async () => {
                    let docCount = await patient_issues.countDocuments(query);
                    myEmitter.emit('count', key, "patientIssues", docCount);
                },
                async () => {
                    let docCount = await patient_events.countDocuments(query);
                    myEmitter.emit('count', key, "patientEvents", docCount);
                },
                async () => {
                    let docCount = await unit_visits.countDocuments(query);
                    myEmitter.emit('count', key, "unitVisits", docCount);
                }
             ]
        });
    
        funcs = funcs.flat();

        documentCountFetchQ.addAll(funcs);
        await documentCountFetchQ.onIdle();
        myEmitter.emit('complete');    
    } catch (e) {
        console.error(e);
    } finally {
        console.log("Closing the connection");
        mongo_connection.close();
    }
}

myEmitter.on('start', () => {
    fetchDocumentStats().catch(e => {
        console.log(e);
    });
});

myEmitter.on('count', (key, field, docCount) => {
    console.log(`${key}: ${field} = ${docCount}`);
    results[key][field] = docCount;
});

myEmitter.on('complete', () => {
    console.log(`Writing Results to ${params.outputFile}`);
    const keys = Object.keys(results);

    const cp_list = keys.map(key => {
        return results[key];
    });

    // console.log(cp_list);

    createCSV(
        params.outputFile,
        [
            {id: 'ID', title: 'ID'},
            {id: 'NAME', title: 'NAME'},
            {id: 'CREATED', title: 'CREATED'},
            {id: 'CREATED (MS)', title: 'CREATED (MS)'},
            {id: 'UPDATED', title: 'UPDATED'},
            {id: 'UPDATED (MS)', title: 'UPDATED (MS)'},
            {id: 'TAGS', title: 'TAGS'},
            {id: 'patientCount', title: 'Patient Count'},
            {id: 'encounterCount', title: 'Encounter Count'},
            {id: 'interactionCount', title: 'Interaction Count'},
            {id: 'enrollmentsCount', title: 'Enrollment Count'},
            {id: 'callAttemptsCount', title: 'Call Attempts Count'},
            {id: 'archivedCallAttemptsCount', title: 'Archived Call Attempts Count'},
            {id: 'patientIssues', title: 'Patient Issues'},
            {id: 'patientEvents', title: 'Patient Events'},
            {id: 'unitVisits', title: 'Unit Visits'}
        ], 
        cp_list
    );    
});

